const router = require("express").Router();
const PDFDocument = require("pdfkit");

function money(n) {
  return `Rs. ${Number(n || 0).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

router.post("/voucher", (req, res) => {
  const { kind, number, date, company, party, items = [], subtotal, gstAmount, total, notes } = req.body;

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="${(number || "voucher").replace(/[^a-zA-Z0-9-_]/g, "_")}.pdf"`);

  const doc = new PDFDocument({ size: "A4", margin: 50 });
  doc.pipe(res);

  const faint = "#6b75a8";
  const ink = "#16213e";

  doc.fillColor(faint).fontSize(9).text((kind || "VOUCHER").toUpperCase(), { characterSpacing: 1 });
  doc.moveDown(0.2);
  doc.fillColor(ink).fontSize(20).font("Helvetica-Bold").text(company?.name || "Company");
  doc.font("Helvetica").fontSize(9).fillColor(faint);
  if (company?.address) doc.text(company.address, { width: 300 });
  if (company?.gst_number) doc.text(`GSTIN ${company.gst_number}`);

  doc.fontSize(11).fillColor(ink).font("Helvetica-Bold").text(number || "", 380, 50, { width: 165, align: "right" });
  doc.font("Helvetica").fontSize(9).fillColor(faint).text(date || "", 380, 68, { width: 165, align: "right" });

  doc.moveDown(2);
  const divY = doc.y + 8;
  doc.moveTo(50, divY).lineTo(545, divY).strokeColor("#dddddd").stroke();
  doc.moveDown(1);

  doc.fontSize(8).fillColor(faint).text(kind?.includes("Sales") ? "BILLED TO" : "PURCHASED FROM", { characterSpacing: 1 });
  doc.fontSize(11).fillColor(ink).font("Helvetica-Bold").text(party?.name || "—");
  doc.font("Helvetica").fontSize(9).fillColor(faint);
  if (party?.address) doc.text(party.address, { width: 300 });
  if (party?.mobile) doc.text(party.mobile);
  if (party?.gstin) doc.text(`GSTIN ${party.gstin}`);

  doc.moveDown(1.5);
  const tTop = doc.y + 8;
  const cols = { item: 50, qty: 290, rate: 350, gst: 420, amount: 470 };

  doc.fontSize(8).fillColor(faint).font("Helvetica-Bold");
  doc.text("ITEM", cols.item, tTop);
  doc.text("QTY", cols.qty, tTop, { width: 50, align: "right" });
  doc.text("RATE", cols.rate, tTop, { width: 60, align: "right" });
  doc.text("GST", cols.gst, tTop, { width: 40, align: "right" });
  doc.text("AMOUNT", cols.amount, tTop, { width: 75, align: "right" });
  doc.moveTo(50, tTop + 14).lineTo(545, tTop + 14).strokeColor("#dddddd").stroke();

  let y = tTop + 22;
  doc.font("Helvetica").fontSize(9).fillColor(ink);
  for (const it of items) {
    if (y > 700) { doc.addPage(); y = 50; }
    doc.text(it.item_name || "", cols.item, y, { width: 230 });
    doc.text(String(it.qty), cols.qty, y, { width: 50, align: "right" });
    doc.text(money(it.rate), cols.rate, y, { width: 60, align: "right" });
    doc.text(`${it.gst_percent}%`, cols.gst, y, { width: 40, align: "right" });
    doc.text(money(it.amount), cols.amount, y, { width: 75, align: "right" });
    y += 20;
  }

  doc.moveTo(50, y + 4).lineTo(545, y + 4).strokeColor("#dddddd").stroke();
  y += 16;
  doc.font("Helvetica").fontSize(9).fillColor(faint);
  doc.text("Subtotal", 380, y, { width: 90, align: "right" }); doc.fillColor(ink).text(money(subtotal), 470, y, { width: 75, align: "right" }); y += 16;
  doc.fillColor(faint).text("GST", 380, y, { width: 90, align: "right" }); doc.fillColor(ink).text(money(gstAmount), 470, y, { width: 75, align: "right" }); y += 18;
  doc.moveTo(380, y).lineTo(545, y).strokeColor("#dddddd").stroke(); y += 8;
  doc.font("Helvetica-Bold").fontSize(12).fillColor(ink);
  doc.text("Total", 380, y, { width: 90, align: "right" });
  doc.text(money(total), 470, y, { width: 75, align: "right" });

  if (notes) {
    y += 40;
    doc.font("Helvetica").fontSize(8).fillColor(faint).text("NOTES", 50, y, { characterSpacing: 1 });
    doc.fontSize(9).fillColor(ink).text(notes, 50, y + 12, { width: 495 });
  }

  doc.fontSize(8).fillColor(faint).text("Generated by SmartERP", 50, 780, { width: 495, align: "center" });
  doc.end();
});

module.exports = router;
